// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AckFailureReason = "not_writer" | "not_found" | "out_of_range" | "invalid_state";

/**
 * All messages that a client (WebSocket or internal HID UI manager) can
 * send to the core.
 */
export type ClientMessage = { "type": "request_write_access", seq: number, } | { "type": "release_write_access", seq: number, } | { "type": "get_state", seq: number, } | { "type": "get_command_set", seq: number, set: string | null, } | { "type": "upsert_command_set", seq: number, set: string | null, base_version?: number | null, commands: Array<MotionCommand>, } | { "type": "update_command", seq: number, index: number, fields: MotionCommandFields, } | { "type": "delete_command_set", seq: number, set: string | null, base_version?: number | null, } | { "type": "list_saved_sets", seq: number, } | { "type": "set_drive_power", seq: number, enabled: boolean, } | { "type": "set_motion_state", seq: number, action: MotionAction, } | { "type": "acknowledge_error", seq: number, };

/**
 * Controller identifier.
 */
export type ControllerId = string;

/**
 * All messages that the core can send to a client.
 *
 * Messages with `seq: Option<u64>` use `Some(n)` when responding to a
 * client request (echoing the client's seq) and `None` when broadcast.
 * Serde serializes `None` by omitting the field, matching the protocol
 * convention that broadcasts have no `seq`.
 */
export type CoreMessage = { "type": "connected", controller_id: ControllerId, limits: SystemLimits, state: CoreState, } | { "type": "ack", seq: number, success: boolean, reason?: AckFailureReason, } | { "type": "write_access_result", seq: number, granted: boolean, holder: ControllerId | null, } | { "type": "command_set", seq: number, set: string | null, version: number, commands: Array<MotionCommand>, } | { "type": "command_result", seq: number, success: boolean, version: number, } | { "type": "saved_set_list", seq: number, sets: Array<SavedSetMetadata>, } | { "type": "state", seq?: number, drive_state: DriveState, active_command_index: number, actual_position: number, demand_position: number, demand_velocity: number, demand_acceleration: number, current_draw: number, drive_temperature: number, motor_temperature: number, warnings: Array<string>, error_code: string | null, command_set_version: number, write_access_holder: ControllerId | null, } | { "type": "command_set_changed", version: number, } | { "type": "write_access_changed", holder: ControllerId | null, previous_holder: ControllerId | null, };

export type CoreState = { drive_state: DriveState, active_command_index: number, actual_position: number, demand_position: number, demand_velocity: number, demand_acceleration: number, current_draw: number, drive_temperature: number, motor_temperature: number, warnings: Array<string>, error_code: string | null, command_set_version: number, write_access_holder: ControllerId | null, };

/**
 * Drive state machine states.
 */
export type DriveState = "disconnected" | "off" | "preparing" | "paused" | "moving" | "errored";

/**
 * Motion control action.
 */
export type MotionAction = "start" | "pause" | "resume" | "stop";

/**
 * A single motion command in a command set.
 */
export type MotionCommand = { position: number, velocity: number, acceleration: number, deceleration: number, };

/**
 * Fields of a motion command that may be partially updated.
 */
export type MotionCommandFields = { position?: number, velocity?: number, acceleration?: number, deceleration?: number, };

/**
 * Metadata for a saved command set, as returned in listings.
 */
export type SavedSetMetadata = { name: string, version: number, saved_at: string, };

export type SystemLimits = { position: number, velocity: number, acceleration: number, deceleration: number, };
